### ISSUE TITLE
Unable to find Electron App when using deep links and custom protocol

### ISSUE THREAD

**Issue by FlushBG** [electron-react-boilerplate/electron-react-boilerplate#3270] opened 2022-07-21 08:49 UTC
## Prerequisites

- [X] Using npm
- [X] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [X] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

To intercept and handle a request to the app's custom protocol

## Current Behavior

Displays the following error:

![image](https://user-images.githubusercontent.com/25154835/180169044-b6f373c3-b5ca-4919-8767-8248f577dae4.png)

## Steps to Reproduce

I created a `Main` class in the `main.ts` file. Here are some points of interest:

**Constructor**
```ts
constructor() {
    app.on('ready', this.createWindow);
    this.registerProtocol();
    this.ensureLock();
  }
```
**createWindow handler**
```ts
private createWindow = async (): Promise<void> => {
    this.mainWindow = new BrowserWindow({
      title: 'REV Clone Padd',
      icon: resolveAssetPath(app.isPackaged, 'icon.png'),
      autoHideMenuBar: true,
      height: 780,
      width: 1024,
      resizable: false,
      webPreferences: {
        devTools: isDebug(),
      },
    });

    this.mainWindow.loadURL(resolveHtmlPath('index.html'));
    this.mainWindow.show();
    if (isDebug()) {
      // this.mainWindow.webContents.openDevTools();
    }
  };
```
**Protocol registration - as described in electron docs**
```ts
private registerProtocol = (): void => {
    app.removeAsDefaultProtocolClient(APP_PROTOCOL);

    if (isAppDev(app) && process.platform === 'win32') {
      app.setAsDefaultProtocolClient(APP_PROTOCOL, process.execPath, [
        path.resolve(process.argv[1]),
      ]);
    } else {
      app.setAsDefaultProtocolClient(APP_PROTOCOL);
    }
  };
```
**Check for primary instance - as described in electron docs**
```ts
 private ensureLock = (): void => {
    const gotTheLock = app.requestSingleInstanceLock();

    if (!gotTheLock) {
      app.quit();
    } else {
      app.on('second-instance', (e, argv) => {
        if (this.mainWindow) {
          if (this.mainWindow.isMinimized()) this.mainWindow.restore();
          this.mainWindow.focus();
        }

        console.log(resolveProtocolUrl(argv));
      });
    }
  };
```
**I am trying to send a deep link request from another React app using** `window.location.assign('protocol://test')`

## Possible Solution (Not obligatory)

I tried the solution, described in #3174 . I either didn't do it right, or the solution doesn't work for me.
It appears the parameters that arrive in `argv ` do not get resolved correctly. `argv[1]` resolves to `--require`.

```ts
app.setAsDefaultProtocolClient(APP_PROTOCOL, process.execPath, [
        path.resolve(process.argv[1]),
]);
```

## Your Environment

- Node version : **14.17.0**
- electron-react-boilerplate version or branch: **main**
- Operating System and version : **Windows 10 Enterprise 10.0.19044**
- Link to your project : **Not handled by source control yet**

**Comment by tilto0822** [comment] 2022-07-22 11:27
Maybe same problem in my issue #3245 
My environment is Node 16.16.0, and using latest stable electron release.

Please check your typescript dev running argument with `process.argv`

**Comment by Tsodinq** [comment] 2022-08-07 04:52
Have you managed to fix this issue?

**Comment by tilto0822** [comment] 2022-08-10 08:24
nope. I try many way, but I still couldn't solve the error.

**Comment by amilajack** [comment] 2022-08-15 22:27
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3245

**Closed by amilajack** 2022-08-15 22:27 UTC
Labels: bug
