### ISSUE TITLE
being able to load up with browser

### ISSUE THREAD

**Issue by iamisti** [electron-react-boilerplate/electron-react-boilerplate#2284] opened 2019-10-21 07:28 UTC
It'd be great if we could have a feature that makes it possible to host the app as a web server, so I can load the application in a browser like a website.

**Comment by amilajack** [comment] 2019-11-23 09:49
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/80

**Closed by amilajack** 2019-11-23 09:49 UTC
Labels: enhancement
