### ISSUE TITLE
ERROR in ./app/components/Home.scss

### ISSUE THREAD

**Issue by aniketbiprojit** [electron-react-boilerplate/electron-react-boilerplate#2528] opened 2020-07-23 20:12 UTC
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js): Error: Cannot find module 'css-loader/locals'

To reproduce change Home.css to Home.scss and the import in Home.tsx

**Comment by Yrlish** [comment] 2020-07-24 08:40
I am sitting here trying to figure what the problem was when upgrading my project from the 1.1.0 boilerplate to 1.2.0.

Happily it wasn't my fault! But it sucks scss files is broken. Will have to wait to upgrade then.

**Comment by aniketbiprojit** [comment] 2020-07-24 09:20
@Yrlish Yeah, I thought so too. I am running a gulpfile to handle .scss bundling and making the webpack ignore the scss files in the  meanwhile. Couldn't figure out how to fix the bug so found a way around it. But, it gets damn annoying to run it.

**Comment by jooohhn** [comment] 2020-07-24 20:24
Duplicate of #2523

**Closed by jooohhn** 2020-07-24 20:24 UTC
Labels: bug
