### ISSUE TITLE
Please include React Dev Tools extension, It's really annoying to develop react apps without them

### ISSUE THREAD

**Issue by hichemfantar** [electron-react-boilerplate/electron-react-boilerplate#2767] opened 2021-02-11 20:12 UTC
Shouldn't an extension like React Dev Tools be included with this react boilerplate?

**Comment by amilajack** [comment] 2021-02-11 20:13
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2725

**Closed by amilajack** 2021-02-11 20:13 UTC
Labels: enhancement
