### ISSUE TITLE
React running in production mode

### ISSUE THREAD

**Issue by guidone** [electron-react-boilerplate/electron-react-boilerplate#2171] opened 2019-03-26 10:43 UTC
Example is not building

```
git clone https://github.com/electron-react-boilerplate/electron-react-boilerplate.git test
cd test
yarn
DEBUG_PROD=true yarn build
DEBUG_PROD=true yarn start
```

I get this on the console.log

![Screen Shot on 2019-03-26 at 11-37-24](https://user-images.githubusercontent.com/502519/54990859-018d6380-4fbc-11e9-960b-301dc43381a2.png)

## Prerequisites

- [X] Using yarn
- [X] Using node 10.x
- [X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [X] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Complile the app

## Current Behavior

Is not compiling the app for production

## Steps to Reproduce (for bugs)

```
git clone https://github.com/electron-react-boilerplate/electron-react-boilerplate.git test
cd test
yarn
DEBUG_PROD=true yarn build
DEBUG_PROD=true yarn start
```

## Your Environment

- Node version : 10.15.0
- Version or Branch used : master
- Operating System and version : MacOs Mojave
- Link to your project : n/a

**Comment by amilajack** [comment] 2019-04-02 16:45
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2148

**Closed by amilajack** 2019-04-02 16:45 UTC
Labels: bug
