### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by ArEnSc** [electron-react-boilerplate/electron-react-boilerplate#3461] opened 2023-04-09 22:01 UTC
## Summary

Just installed this it works I think 
ran npm install and 
npm start.

[96020:0409/175958.099584:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://aiijjhiobblgkeecgfeiehbbkilbklch/build/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
  ID:      aiijjhiobblgkeecgfeiehbbkilbklch
  Type:    RuntimeError
  Context: chrome-extension://aiijjhiobblgkeecgfeiehbbkilbklch/build/background.js
  Stack Trace: 
    {
      Line:     107
      Column:   1
      URL:      chrome-extension://aiijjhiobblgkeecgfeiehbbkilbklch/build/background.js
      Function: (anonymous function)
    }
[96020:0409/175958.099997:ERROR:extensions_browser_client.cc(62)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      aiijjhiobblgkeecgfeiehbbkilbklch
  Type:    ManifestError
IPC test: ping
[96020:0409/175958.929370:ERROR:CONSOLE(2)] "Electron sandboxed_renderer.bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (2)
[96020:0409/175958.929395:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (2)

**Comment by Leka74** [comment] 2023-04-10 01:56
Caused by the `REACT_DEVELOPER_TOOLS` extension @ `src/main/main.ts`

**Comment by Leka74** [comment] 2023-04-10 16:06
It just means that the react developer tools extension isn't being loaded properly. You can read more about it here:
https://github.com/electron/electron/issues/36545 & https://github.com/facebook/react/issues/25843.

You can either look through those issues and see if there is a fix, or just remove the `REACT_DEVELOPER_TOOLS` from the extensions array in `main.ts`

**Comment by amilajack** [comment] 2023-06-04 02:51
duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3419

**Closed by amilajack** 2023-06-04 02:51 UTC
Labels: question
