### ISSUE TITLE
problem adding a new route to the file routes.json

### ISSUE THREAD

**Issue by willerpp** [electron-react-boilerplate/electron-react-boilerplate#2510] opened 2020-07-01 14:32 UTC
Hi, guys, I have downloaded your project ( very good ) and I started playing around with him, I was trying to add new functionality, and in the point of adding the new route,  it gives me an error, I can't add a new route constant to the file routes.json, I don't know why but it doesn't work when I use the new route, any advice?

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Well my new route should work, but instead, the app doesn't show the main screen.

## Current Behavior
The app doesn't show the home page

## Steps to Reproduce (for bugs)

1. Change the routes.sjon with this code :
{
  "HOME": "/",
  "COUNTER": "/counter",
  "PEPE": "/customer"
}

2.Add to the routes.tsx with this code 
import CustomerPage from './containers/CustomerPage'; 

<Route exact path={"/customer"} component={CustomerPage} />  

3. Of course, you need to create a new component called CustomerPage, just take the home component and renamed and put inside it a different text from the home screen.

4. I have added a toolbar from material UI that works perfectly, I'm going to upload my project with this link and you can see what I say.

## Context
I'm trying to create an app and i need to add new routes and new screens to the project

## Your Environment

- Node version : 12.18.0
- Version or Branch used : last one 
- Operating System and version : Windows 10
- Link to your project : my project is in my pc, i dont have any version published in any site, if you need 

thank you so much

**Comment by TheProof2k2** [comment] 2020-07-12 11:44
Hi guys, I can confirm this behaviour, I've the same bug. New Routes to new custom components don't work.

**Comment by AndreoliBR** [comment] 2020-07-14 00:29
Yes, this happened with me too. I've tried almost everything to fix this.

**Comment by jooohhn** [comment] 2020-07-22 02:27
Could you guys tell me what version of electron-react-boilerplate you're using? It might be a bug related to the #2465 v1.2.0 release

**Comment by tomperr** [comment] 2020-07-22 11:58
Hi, same problem for me using 1.2.0 version (node 12.11.1).

**Comment by callren** [comment] 2020-08-06 04:36
this happened with me too. I've tried almost everything to fix this.

**Comment by amilajack** [comment] 2020-08-14 03:02
What version of ERB are you using?

**Comment by jooohhn** [comment] 2020-08-14 03:45
I couldn't reproduce on v1.3.0. I think may be related to the order of your `<Routes>` in `routes.tsx`

This example will render `HomePage` instead of `CustomerPage`. React-router's [Switch](https://reactrouter.com/web/api/Switch) component renders the first child `<Route>` that matches the URL (basically `/customer` matches the path `/` first and renders `HomePage`)

```js
<Switch>
  <Route path={routes.COUNTER} component={CounterPage} />
  <Route path={routes.HOME} component={HomePage} />
  <Route path={routes.CUSTOMER} component={CustomerPage} />
</Switch>
```

If this is the case, the problem can be fixed by ordering routes by COUNTER -> CUSTOMER -> HOME or using the [exact property](https://reactrouter.com/web/api/Route/exact-bool)

**Comment by SingularityF** [comment] 2020-08-14 20:13
> 
> 
> I couldn't reproduce on v1.3.0. I think may be related to the order of your `<Routes>` in `routes.tsx`
> 
> This example will render `HomePage` instead of `CustomerPage` even if the given path is `/customer`. React-router's [Switch](https://reactrouter.com/web/api/Switch) component renders the first child `<Route>` that matches the URL (basically `/customer` matches the path `/` first and renders `HomePage`)
> 
> ```js
> <Switch>
>   <Route path={routes.COUNTER} component={CounterPage} />
>   <Route path={routes.HOME} component={HomePage} />
>   <Route path={routes.CUSTOMER} component={CustomerPage} />
> </Switch>
> ```
> 
> If this is the case, the problem can be fixed by ordering routes by COUNTER -> CUSTOMER -> HOME or using the [exact property](https://reactrouter.com/web/api/Route/exact-bool)

I was facing the same issue and adding `exact` worked for me.

**Closed** 2020-08-15 02:12 UTC
Labels: bug, waiting-for-response
