### ISSUE TITLE
Preload.js is not a module - Unable to load preload script; Unexpected token 'export'

### ISSUE THREAD

**Issue by Rafatcb** [electron-react-boilerplate/electron-react-boilerplate#2974] opened 2021-09-06 14:06 UTC
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

The `preload.js` file should be handled as a module, so I would be able to use `import` statements in it, among other things.

## Current Behavior

When I use `import` in `preload.js`, it throws an error:

> Cannot use import statement outside a module

Trying to avoid the use of `import`s leads to other errors, so I thoguht it would be better to handle `preload.js` as a module.

## Steps to Reproduce

1. Clone this repo.

2. Create a file `src/main/helper.ts` with the following content:
```javascript
export const helper = () => {
  console.log('helped!');
};
```

3. Import it in `preload.js`:
```javascript
// ...
// import { helper } from './helper'; // This throws an error: Cannot use import statement outside a module
// const { helper } = require('./helper'); // This throws an error: Cannot find module './helper'
const { helper } = require('./helper.ts'); // I don't know if this will be a problem in production, since I need to
                                           // provide the file extension

contextBridge.exposeInMainWorld('electron', {
  help: helper,
  // ...
}
```

4. Run `yarn start` and see the console:

```javascript
VM496 renderer_init.js:93 Unable to load preload script: C:\path\electron-react-boilerplate-main\src\main\preload.js
(anonymous) @ VM496 renderer_init.js:93
./lib/renderer/init.ts @ VM496 renderer_init.js:93
__webpack_require__ @ VM496 renderer_init.js:1
(anonymous) @ VM496 renderer_init.js:1
___electron_webpack_init__ @ VM496 renderer_init.js:1
(anonymous) @ VM496 renderer_init.js:165
compileForInternalLoader @ VM431 loaders.js:283
compileForPublicLoader @ VM431 loaders.js:225
loadNativeModule @ VM471 helpers.js:35
Module._load @ VM464 loader.js:747
f._load @ VM491 asar_bundle.js:5
executeUserEntryPoint @ VM490 run_main.js:72
(anonymous) @ VM459 run_main_module.js:17
VM496 renderer_init.js:93 C:\path\electron-react-boilerplate-main\src\main\helper.ts:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export const helper = () => {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at wrapSafe (internal/modules/cjs/loader.js:974:15)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
```

## Possible Solution (Not obligatory)

I'm still trying to figure it out 🤷‍♂️. It looks like this could be fixed using Webpack (see [How do I compile a preload script w/ webpack in Electron?](https://stackoverflow.com/a/63481483/8839059)), but I'm far away of being an expert in it, so I didn't find a solution yet.

## Context

I have some files in `/main` folder that I want to import to `preload.js` in order to have access to its methods from Renderer process. For example, I have an `IpcService` like the one in [this article](https://blog.logrocket.com/electron-ipc-response-request-architecture-with-typescript/), and this file makes use of `import` statements and `export`. That's why I need `preload.js` to be able handled as a module, such as the rest of the project.

## Your Environment

- Node version : v14.15.4
- electron-react-boilerplate version or branch : main (3.0.2)
- Operating System and version : Windows 10 verison 21H1 (19043.1165)
- Link to your project : - (_i just cloned this repo and reproduced it as mentioned in **Steps to Reproduce**_)

**Comment by thepasto** [comment] 2021-11-07 06:34
Any news on this?

**Comment by guillermoriv** [comment] 2021-11-07 10:40
TypeScript **cannot** be executed from a browser / node.js environment directly. At first you have to transpile it into native javascript. So it cannot be executed in a `javascript` file code from a `typescript` file. The funny thing is that you can do it viceversa, you can import `javascript` files into `typescript` files, so this is not a bug, is more like it **CANNOT** be done as you can see for my explanation above.

**Possible solution:**

Just create a preload folder and then just use `.js` files for this, and you can import that to any `.ts` files that you want and work fine with it (that's how I am doing in it).

**Comment by thepasto** [comment] 2021-11-07 12:11
It is a great explanation, thanks. i hope it helps everyone as it helped me.
For me it is the first time that I try to run a react app  in a desktop environement, many things are not immediate even reading the documentation. Thanks again

**Comment by Rafatcb** [comment] 2021-11-09 13:14
@guillermoriv I understand that, but I'm looking for a solution like what happens with `main.ts` today, that you can write code in TypeScript and it is transpiled to JavaScript on runtime, as you mentioned that it works with `npm run build`.

As I mentioned in the issue, [How do I compile a preload script w/ webpack in Electron?](https://stackoverflow.com/a/63481483/8839059) would probably help, but I'd need to spend some time into this to understand better how Webpack works and how to do so with electron-react-boilerplate.

**Comment by amilajack** [comment] 2021-12-28 01:12
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3058

**Closed by amilajack** 2021-12-28 01:12 UTC
Labels: bug

**Comment by michaelprescott** [comment] 2022-08-12 11:25
In case anyone lands in this thread in 2022.

No browsers that I'm aware of run TypeScript.  You must transpile to JavaScript.

Remember, the main process of an Electron app is run by NodeJS, the renderer process is run within Chromium, BUT the preload process is also within Chromium.  Preload is just a special case, which has the contextBridge and ipcRenderer from electron.  This is so you can build a bridge between the renderer (UI) and the main process.  This also means that short of those two electron types, you cannot do fancy Node things, and you cannot do `import { yourOwn } from "./your-own-module.js"`.  Nor can you `import "./your-own.js"`.  You can't even `const yourOwn = require("./your-own-module.js")` even though all of those are technically correct.  You can't do this EVEN if you already transpiled your TS versions of those into JS.

There are two solutions:
You can overcome that limitation by setting webPreferences.nodeIntegration = true when you create your BrowserWindow, just be sure to read about the risks of doing so. (You still have to transpile TS to JS, but now your imports of your own modules will work.)

Or you can use a bundler to combine all of your previously transpiled preload modules into a single preload.js.  This is what Rafatcb was beginning to investigate above.

**Comment by Pomax** [comment] 2025-07-10 00:14
I'm not sure why this thread focussed on TS so much when the original comment was clearly about a _JavaScript_ preload.js, not a TypeScript preload.ts (and so is very much not a duplicate of #3058): ESM landed in JS and received both Node _and_ browser support years before this issue was filed.

Even in 2025, a preload.js that uses a perfectly normal ESM `import` statement throws an error about that in Electron v37, even when Electron itself can run ESM perfectly fine. Somehow, Electron and the web view undertand modules but the preload handling magically doesn't, and that's still a really weird bug that should get fixed. There is no reason for electron to not be able to "shim" the import for its own libraries inside a preload.js

**Comment by michaelprescott** [comment] 2025-07-10 10:13
I have zero recollection of writing the above, but for time-traveling fun reviewed anyway.  It looks like a focus of the conversation was on TS because Rafatcb's code tried several attempts with latest showing they were using TS.  I'd wager that we all had encountered the same problem and TypeScript was in our workflow as well.

`
// ...

// import { helper } from './helper'; // This throws an error: Cannot use import statement outside a module

// const { helper } = require('./helper'); // This throws an error: Cannot find module './helper'

const { helper } = require('./helper.ts'); // I don't know if this will be a problem in production, since I need to
                                           // provide the file extension
`

**Comment by maheshbansod** [comment] 2025-09-08 16:06
Anyone able to figure out using ESM for the preload script?

I'm now considering having a separate tsconfig just for the preload script then which will emit commonjs, this solution feels kinda awkward tbh

----

Edit: After thinking on this more, and implementing various approaches, I have come to the conclusion to that it makes sense for the preload script to be a single bundle instead of a "runtime entity" that imports from other files.
So, I went with bundling the preload script and it's dependencies in a single commonjs bundle in a build step, while using ESM for development.

**Comment by Pomax** [comment] 2026-02-07 18:52
@amilajack this was never a duplicate, and the linked PRs never fixed the issue as filed (the issue shows a helper.ts but this is effectively irrelevant as the problem is the preload.js file being flagged as erroneous for using plain JS ESM import syntax, something that's still broken in v40) - can this be reopened so that it can get a proper fix still?

**Comment by JonasGruenwald** [comment] 2026-02-24 19:47
Just ran into this is well, surprising to see since ESM imports seem to work fine for main and renderer, it's just preload that only seems to work with CommonJS modules. I don't really want to use a bundler just for this one script, would be great if the issue could be addressed.

**Comment by Pomax** [comment] 2026-02-24 23:52
note that you don't need a bundler, you can just give it a `cjs` extension and it'll work, but it's still really odd that this part still can't work with ESM (even if under the hood it needs to be an `import(...)` rather than a top level import).

**Comment by JonasGruenwald** [comment] 2026-02-25 10:17
> note that you don't need a bundler, you can just give it a `cjs` extension and it'll work, but it's still really odd that this part still can't work with ESM (even if under the hood it needs to be an `import(...)` rather than a top level import).

Right, but I do want to import types from my other ESM modules into the preload script for my API definition. Importing ESM modules into CJS with `import(...)` is a bit annoying and I'm not sure if it's possible with types. I think I'd have to do something like tell typescript to output CJS instead of ESM and I don't want that for my whole project so I'd have to add another tsconfig.

But anyways, I just noticed I commented on the wrong repo I think? I am not using any react boilerplate or anything like that, I consider this an Electron issue unless I'm mistaken, just found this issue through a web search
