### ISSUE TITLE
hot reload main process?

### ISSUE THREAD

**Issue by hellojayjay** [electron-react-boilerplate/electron-react-boilerplate#2727] opened 2021-01-13 02:13 UTC
## Summary

Is there any way to hot reload main process when changing main process typescript files?

**Comment by cazzer** [comment] 2021-03-12 00:28
Possible duplicate of #2141

**Comment by amilajack** [comment] 2021-03-12 00:55
Closing as duplicate. There are ways to do this but none are stable since the last time I investigated this.

**Closed** 2021-03-12 00:54 UTC
Labels: question
