### ISSUE TITLE
 Is hot reloading possible in main.ts?

### ISSUE THREAD

**Issue by WachsenHaus** [electron-react-boilerplate/electron-react-boilerplate#3109] opened 2022-01-11 12:29 UTC
## Summary

 
 I want code changes in main.ts to be applied quickly.
 
 The part I mostly modify is ipcmain.handle.
 
 I can't figure out a way at all.
 
 Tired of typing control + c and npm run start every time.
 
 Please help me
 
 
  // Is it best to do control+C and npm run start when I change something here?
  // Is there a better way ?
  
  
![choi](https://user-images.githubusercontent.com/59411545/148942553-fbbf6e6f-67c4-475c-8f5b-6469adb88f8d.PNG)

**Comment by kbrisso** [comment] 2022-01-17 03:40
I did some quick digging and the main process is kicked off with this script line in the package file. 
`"start:main": "cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts",`

You can probably add electronmon package and change the above line to reflect below to get hot reload. Not guaranteed nber tried it, but let me know how it works if you do.
`npx electronmon -r`
https://www.npmjs.com/package/electronmon

If needed you can kick off main by itself then renderer - it might help you with dev time and reload.

**Comment by amilajack** [comment] 2022-02-09 18:06
Duplicate of #2141

**Closed by amilajack** 2022-02-09 18:06 UTC
Labels: question
