### ISSUE TITLE
`yarn dev` and `npm run dev` don't show a dev window of the app

### ISSUE THREAD

**Issue by darthdeus** [electron-react-boilerplate/electron-react-boilerplate#2387] opened 2020-02-26 00:59 UTC
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

An electron window should open with the app loaded.

## Current Behavior

Running `yarn dev` starts up all the subprocesses but no electron window is shown

```
PS C:\dev\your-project-name> yarn dev
yarn run v1.22.0
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...

> electron-react-boilerplate@1.0.0 start-main-dev C:\dev\your-project-name
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts
```

## Steps to Reproduce (for bugs)

1. `git clone --depth 1 --single-branch --branch master https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name`

2. `cd your-project-name`

3. `yarn`

4. `yarn dev`

## Your Environment

- Node version : tried 10.x, 12.x and 13.x
- Version or Branch used : master
- Operating System and version : Windows 10

**Comment by lafis** [comment] 2020-02-26 14:44
Duplicate of #2327
does this [2327#issuecomment-569184150](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2327#issuecomment-569184150) help?

> Try turning off dark mode in Win10.
> 
> [electron/electron#19468](https://github.com/electron/electron/issues/19468)

**Closed** 2020-02-26 14:46 UTC
Labels: bug
