### ISSUE TITLE
Lots of warnings on fresh install

### ISSUE THREAD

**Issue by dev2648e** [electron-react-boilerplate/electron-react-boilerplate#2685] opened 2020-12-11 19:42 UTC
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
- No warnings are shown on fresh install

## Current Behavior
- I see a bunch of warnings, which IMO can be easily fixed (if I've a cent for every time I heard that).

## Steps to Reproduce
- git clone git@github.com:electron-react-boilerplate/electron-react-boilerplate.git
- cd electron-react-boilerplate
- yarn 

```
>yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.2.1: The platform "win32" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > enzyme-adapter-react-16@1.15.5" has incorrect peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.5" has incorrect peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.13.1" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-import-resolver-webpack@^0.12.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-plugin-jest@^23.13.2".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
warning " > eslint-config-erb@2.0.0" has unmet peer dependency "eslint-plugin-testcafe@^0.2.1".
warning " > eslint-config-erb@2.0.0" has incorrect peer dependency "react@^16.13.1".
warning " > optimize-css-assets-webpack-plugin@5.0.4" has incorrect peer dependency "webpack@^4.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.5", while you're on "1.22.4".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=C:\my-home\Projects\client-thameem-ai-face-electron\test-react-electron-starter-v2\src
yarn run v1.22.4
$ C:\my-home\Projects\client-thameem-ai-face-electron\test-react-electron-starter-v2\node_modules\.bin\cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
[webpack-cli] Compilation finished
asset renderer.dev.dll.js 2.38 MiB [emitted] (name: renderer)
runtime modules 1.03 KiB 5 modules
cacheable modules 2.07 MiB 188 modules
20 modules

WARNING in ./node_modules/electron-debug/index.js 108:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[0]

WARNING in ./node_modules/electron-debug/index.js 109:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[0]

webpack 5.5.1 compiled with 2 warnings in 2528 ms
Done in 6.50s.
Thank you for using electron-react-boilerplate!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/electron-react-boilerplate-594/donate

Done in 197.53s.
```

## Possible Solution (Not obligatory)

- add proper peer dependencies. That will sort out quite a few warnings

## Context
- Fresh clone and install, nothing changed

## Your Environment

- Node version :
>node -v
v14.7.0
- electron-react-boilerplate version or branch :
latest master:
commit 37789b17121d920818c68a54cd1bf33e89f2903a (HEAD -> master, origin/master, origin/HEAD)
Author: Amila Welihinda <amilajack@gmail.com>
Date:   Thu Dec 10 22:31:46 2020 -0800

    feat: publish new release
- Operating System and version :
Microsoft Windows [Version 10.0.18363.1198]
- Link to your project :
- same as original project
git@github.com:electron-react-boilerplate/electron-react-boilerplate.git

**Comment by mtalhagaoglu** [comment] 2020-12-15 11:01
Hi. I have same error. Do we have a solution for that?

**Comment by amilajack** [comment] 2020-12-15 18:17
These are not errors, these are warnings. @jooohhn is taking a look at this

**Comment by amilajack** [comment] 2020-12-15 18:22
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2558

**Closed by amilajack** 2020-12-15 18:22 UTC
Labels: bug

**Comment by zerocewl** [comment] 2020-12-16 08:52
Lol, he is doing this for 4 months.
Have you looked at the depended issue? 
There is no descripition and no progress.
Even the stale bot has noted this outdated issue.
